project_id = "qjvctpmpxeadawbigroz"

[functions.payhip-webhook]
verify_jwt = false

[functions.payhip-lookup]
verify_jwt = false


[functions.training]
verify_jwt = false

[functions.training-automation]
verify_jwt = false

[functions.portal]
verify_jwt = false

[functions.samgov-credentials]
verify_jwt = false
